# Linear algebra

In [1]:
import numpy as np

In [2]:
np.__version__

'2.2.3'

## Matrix and vector products

Q1. Predict the results of the following code.

In [5]:
x = [1,2]
y = [[4, 1], [2, 2]]
#print np.dot(x, y)
#print np.dot(y, x)
#print np.matmul(x, y)
#print np.inner(x, y)
#print np.inner(y, x)
Prediction:
[8 5]
[6 6]
[8 5]
[6 6]
[6 6]

[8 5]
[6 6]
[8 5]
[6 6]
[6 6]


Q2. Predict the results of the following code.

In [ ]:
x = [[1, 0], [0, 1]]
y = [[4, 1], [2, 2], [1, 1]]
#print np.dot(y, x)
#print np.matmul(y, x)
Prediction:
[[4 1]
 [2 2]
 [1 1]]
[[4 1]
 [2 2]
 [1 1]]

Q3. Predict the results of the following code.

In [10]:
x = np.array([[1, 4], [5, 6]])
y = np.array([[4, 1], [2, 2]])
#print np.vdot(x, y)
#print np.vdot(y, x)
#print np.dot(x.flatten(), y.flatten())
#print np.inner(x.flatten(), y.flatten())
#print (x*y).sum()
Prediction:
30
30
30
30
30

30

Q4. Predict the results of the following code.

In [12]:
x = np.array(['a', 'b'], dtype=object)
y = np.array([1, 2])
#print np.inner(x, y)
#print np.inner(y, x)
#print np.outer(x, y)
#print np.outer(y, x)
Prediction:
abb
abb
[['a' 'aa']
 ['b' 'bb']]
[['a' 'b']
 ['aa' 'bb']]

## Decompositions

Q5. Get the lower-trianglular `L` in the Cholesky decomposition of x and verify it.

In [14]:
x = np.array([[4, 12, -16], [12, 37, -43], [-16, -43, 98]], dtype=np.int32)
L = np.linalg.cholesky(x)
print (L)
assert np.array_equal(np.dot(L, L.T.conjugate()), x)

[[ 2.  0.  0.]
 [ 6.  1.  0.]
 [-8.  5.  3.]]


Q6. Compute the qr factorization of x and verify it.

In [22]:
x = np.array([[12, -51, 4], [6, 167, -68], [-4, 24, -41]], dtype=np.float32)
q, r = np.linalg.qr(x)
print ("q=", q, "\nr=", r)
assert np.allclose(np.dot(q, r), x)

q= [[-0.85714287  0.3942857   0.33142856]
 [-0.42857143 -0.9028571  -0.03428571]
 [ 0.2857143  -0.17142858  0.94285715]] 
r= [[ -14.  -21.   14.]
 [   0. -175.   70.]
 [   0.    0.  -35.]]


Q7. Factor x by Singular Value Decomposition and verify it.

In [25]:
x = np.array([[1, 0, 0, 0, 2], [0, 0, 3, 0, 0], [0, 0, 0, 0, 0], [0, 2, 0, 0, 0]], dtype=np.float32)
U, s, V = np.linalg.svd(x, full_matrices=False)
print ("U=", U, "\ns=", s, "\nV=", V)
assert np.allclose(np.dot(U, np.dot(np.diag(s), V)), x)

U= [[ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  0.  1.]
 [ 0.  0. -1.  0.]] 
s= [3.       2.236068 2.       0.      ] 
V= [[-0.         0.         1.        -0.         0.       ]
 [ 0.4472136  0.         0.         0.         0.8944272]
 [ 0.        -1.         0.         0.         0.       ]
 [ 0.         0.         0.         1.         0.       ]]


## Matrix eigenvalues

Q8. Compute the eigenvalues and right eigenvectors of x. (Name them eigenvals and eigenvecs, respectively)

In [28]:
x = np.diag((1, 2, 3))
y = np.linalg.eig(x)[0]
t = np.linalg.eigvals(x)
assert np.array_equal(y, t)
print ("eigenvalues are\n", y)
y = np.linalg.eig(x)[1]
print ("eigenvectors are\n", y)

eigenvalues are
 [1. 2. 3.]
eigenvectors are
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Q9. Predict the results of the following code.

In [31]:
#print np.array_equal(np.dot(x, eigenvecs), eigenvals * eigenvecs)
prediction:
true

SyntaxError: invalid syntax (3480842295.py, line 2)

## Norms and other numbers

Q10. Calculate the Frobenius norm and the condition number of x.

In [33]:
x = np.arange(1, 10).reshape((3, 3))
y=np.linalg.norm(x, 'fro')
z=np.linalg.cond(x, 'fro')
print (y)
print (z)

16.881943016134134
inf


Q11. Calculate the determinant of x.

In [34]:
x = np.arange(1, 5).reshape((2, 2))
x = np.arange(1, 5).reshape((2, 2))
y1 = np.linalg.det(x)
y2 = x[0, 0] * x[1, 1] - x[0, 1] * x[1, 0]
assert np.allclose(y1, y2)
print (y1)

-2.0000000000000004


Q12. Calculate the rank of x.

In [35]:
x = np.eye(4)
y1 = np.linalg.matrix_rank(x)
y2 = np.linalg.svd(x)[1].size
assert y1 == y2
print (y1)

4


Q13. Compute the sign and natural logarithm of the determinant of x.

In [37]:
x = np.arange(1, 5).reshape((2, 2))
z, a = np.linalg.slogdet(x)
y = np.linalg.det(x)
assert z == np.sign(y)
assert a == np.log(np.abs(y))
print (z, a)

-1.0 0.6931471805599455


Q14. Return the sum along the diagonal of x.

In [40]:
x = np.eye(4)
y1 = np.trace(x)
y2 = x.diagonal().sum()
assert y1 == y2
print (y1)

4.0


## Solving equations and inverting matrices

Q15. Compute the inverse of x.

In [41]:
x = np.array([[1., 2.], [3., 4.]])
y = np.linalg.inv(x)
assert np.allclose(np.dot(x, y), np.eye(2))
print (y)

[[-2.   1. ]
 [ 1.5 -0.5]]
